In [2]:
import pandas as pd
from google.colab import files

print("Upload bloudan_restaurant_1000.xlsx")
uploaded = files.upload()

df = pd.read_excel("bloudan_restaurant_1000.xlsx")
df.head()

Upload bloudan_restaurant_1000.xlsx

Saving bloudan_restaurant_1000.xlsx to bloudan_restaurant_1000.xlsx

,ID_Commande,ID_Client,Nom_Client,Téléphone,Pays,Plat,Prix,Quantité,Date,Note,Commentaire,Stock,Canal
0,1,6191,Fatma,49523734972,Syrie,Taboulé,12.36,2,2025-03-24,4,Ambiance agréable.,84,À emporter
1,2,2685,Lea,49342285876,Allemagne,Kebbé,17.58,2,2025-04-18,4,Personnel gentil.,11,Sur place
2,3,9666,Amine,49580404538,Tunisie,Brochettes mixtes,9.60,3,2025-04-02,5,Un peu salé.,64,Sur place
3,4,6393,Leila,49954206851,Tunisie,Kebbé,17.19,1,2025-01-14,5,Très bon goût.,18,Livraison
4,5,6486,Noah,49887110843,Allemagne,Shawarma viande,5.71,2,2025-01-08,5,Un peu salé.,87,Sur place

In [3]:
import pandas as pd
from google.colab import files

print("⬆️ Upload bloudan_restaurant_1000.xlsx")
uploaded = files.upload()

df = pd.read_excel("bloudan_restaurant_1000.xlsx")
df.head()

⬆️ Upload bloudan_restaurant_1000.xlsx

Saving bloudan_restaurant_1000.xlsx to bloudan_restaurant_1000 (1).xlsx

,ID_Commande,ID_Client,Nom_Client,Téléphone,Pays,Plat,Prix,Quantité,Date,Note,Commentaire,Stock,Canal
0,1,6191,Fatma,49523734972,Syrie,Taboulé,12.36,2,2025-03-24,4,Ambiance agréable.,84,À emporter
1,2,2685,Lea,49342285876,Allemagne,Kebbé,17.58,2,2025-04-18,4,Personnel gentil.,11,Sur place
2,3,9666,Amine,49580404538,Tunisie,Brochettes mixtes,9.60,3,2025-04-02,5,Un peu salé.,64,Sur place
3,4,6393,Leila,49954206851,Tunisie,Kebbé,17.19,1,2025-01-14,5,Très bon goût.,18,Livraison
4,5,6486,Noah,49887110843,Allemagne,Shawarma viande,5.71,2,2025-01-08,5,Un peu salé.,87,Sur place

In [4]:
import pandas as pd
from google.colab import files

print("⬆️ Upload bloudan_restaurant_1000.xlsx")
uploaded = files.upload()

df = pd.read_excel("bloudan_restaurant_1000.xlsx")
df.head()

⬆️ Upload bloudan_restaurant_1000.xlsx

Saving bloudan_restaurant_1000.xlsx to bloudan_restaurant_1000 (2).xlsx

,ID_Commande,ID_Client,Nom_Client,Téléphone,Pays,Plat,Prix,Quantité,Date,Note,Commentaire,Stock,Canal
0,1,6191,Fatma,49523734972,Syrie,Taboulé,12.36,2,2025-03-24,4,Ambiance agréable.,84,À emporter
1,2,2685,Lea,49342285876,Allemagne,Kebbé,17.58,2,2025-04-18,4,Personnel gentil.,11,Sur place
2,3,9666,Amine,49580404538,Tunisie,Brochettes mixtes,9.60,3,2025-04-02,5,Un peu salé.,64,Sur place
3,4,6393,Leila,49954206851,Tunisie,Kebbé,17.19,1,2025-01-14,5,Très bon goût.,18,Livraison
4,5,6486,Noah,49887110843,Allemagne,Shawarma viande,5.71,2,2025-01-08,5,Un peu salé.,87,Sur place

In [6]:
!pip install unidecode langdetect transformers sentencepiece -q

def normalize_text(text: str) -> str:
    return text.lower()

from langdetect import detect, LangDetectException
from difflib import SequenceMatcher

from transformers import pipeline

ImportError: cannot import name 'GenerationMixin' from 'transformers.generation' (/usr/local/lib/python3.12/dist-packages/transformers/generation/__init__.py)

In [ ]:
# ==================================================
# CHATBOT BLOUDAN – CODE COMPLET (ONE CELL)
# ==================================================

# -------- 1) DETECT LANGUAGE (simple & stable)
def detect_lang(text):
    t = text.lower()
    if any(c in text for c in ["أ","ش","ك","ل","ي","ف","ن","ت","م","ر"]):
        return "ar"
    if any(w in t for w in ["ich","bestellen","essen","kann","möchte","bitte","wo"]):
        return "de"
    if any(w in t for w in ["can","order","open","where","menu","please"]):
        return "en"
    return "fr"


# -------- 2) DETECT INTENT
def detect_intent_from_text(text, role="client"):
    t = text.lower()

    if role == "client":
        if any(w in t for w in ["commande","comande","order","bestellen","اطلب","أطلب","طلب"]):
            return "faire_commande"
        if any(w in t for w in ["menu","plat","plats","essen","eat","منيو","أكل","اكل"]):
            return "demande_menu"
        if any(w in t for w in ["recommend","recommande","empfehlen","تقترح","تنصح"]):
            return "recommandation_plat"
        if any(w in t for w in ["hour","open","horaire","adresse","wo","où","وين","فين"]):
            return "infos_restaurant"
        return "salutation"

    return "salutation"


# -------- 3) SIMPLE SENTIMENT ANALYSIS
def analyser_sentiment_texte(text):
    t = text.lower()
    if any(w in t for w in ["merci","good","great","excellent","ممتاز","شكرا","top"]):
        return {"label": "POSITIVE", "score": 0.9}
    if any(w in t for w in ["bad","problem","late","سيء","غالي","مش باهي"]):
        return {"label": "NEGATIVE", "score": 0.8}
    return {"label": "NEUTRAL", "score": 0.6}


# -------- 4) MULTI-LANGUAGE RESPONSES
def repondre_salutation(lang):
    return {
        "fr": "Bonjour 👋 Bienvenue chez Bloudan Restaurant. Comment je peux t’aider ?",
        "en": "Hello 👋 Welcome to Bloudan Restaurant. How can I help you?",
        "de": "Hallo 👋 Willkommen im Bloudan Restaurant. Wie kann ich helfen?",
        "ar": "أهلاً 👋 مرحبا بيك في مطعم بلودان. كيفاش نجم نعاونك؟"
    }[lang]

def repondre_demande_menu(lang):
    return {
        "fr": "📋 Notre menu : Shawarma, Falafel, Kebbé, Hummus.",
        "en": "📋 Our menu: Shawarma, Falafel, Kebbeh, Hummus.",
        "de": "📋 Unser Menü: Shawarma, Falafel, Kibbeh, Hummus.",
        "ar": "📋 المنيو فيه: شاورما، فلافل، كبة، حمص."
    }[lang]

def repondre_recommandation_plat(lang):
    return {
        "fr": "⭐ Je te recommande le Shawarma poulet.",
        "en": "⭐ I recommend the chicken shawarma.",
        "de": "⭐ Ich empfehle das Hähnchen-Shawarma.",
        "ar": "⭐ نقترح عليك شاورما الدجاج."
    }[lang]

def repondre_infos_restaurant(lang):
    return {
        "fr": "📍 Bloudan Restaurant – ouvert de 11h à 23h.",
        "en": "📍 Bloudan Restaurant – open from 11am to 11pm.",
        "de": "📍 Bloudan Restaurant – geöffnet von 11 bis 23 Uhr.",
        "ar": "📍 مطعم بلودان – مفتوح من 11 إلى 23."
    }[lang]

def repondre_faire_commande(lang):
    return {
        "fr": "✅ Bien sûr. Dis-moi le plat et la quantité.",
        "en": "✅ Sure. Tell me the dish and the quantity.",
        "de": "✅ Natürlich. Sag mir das Gericht und die Menge.",
        "ar": "✅ أكيد. قولي شنوّة الطبق والكمية."
    }[lang]


# -------- 5) DISPATCHER
def chatbot_dispatcher(role, intent, lang):
    if role == "client":
        if intent == "salutation":
            return repondre_salutation(lang)
        if intent == "demande_menu":
            return repondre_demande_menu(lang)
        if intent == "recommandation_plat":
            return repondre_recommandation_plat(lang)
        if intent == "infos_restaurant":
            return repondre_infos_restaurant(lang)
        if intent == "faire_commande":
            return repondre_faire_commande(lang)
        return repondre_salutation(lang)
    else:
        return "Admin mode."


# -------- 6) CHAT LOOP
def discuter_avec_chatbot(role="client"):
    print("💬 Chatbot Bloudan – mode", role)
    print("Écris 'exit' pour quitter.\n")

    while True:
        user_text = input("🧑‍💻 Toi : ")

        if user_text.strip().lower() in ["exit", "quit", "stop", "خروج"]:
            print("👋 Fin de la conversation.")
            break

        lang = detect_lang(user_text)
        intent = detect_intent_from_text(user_text, role=role)
        bot_reply = chatbot_dispatcher(role, intent, lang)
        sentiment = analyser_sentiment_texte(user_text)

        print(f"🤖 Bot (intent={intent}, lang={lang}) : {bot_reply}")
        print(f"🧠 Sentiment : {sentiment['label']} (score={sentiment['score']})")
        print("-" * 60)


# -------- 7) RUN CHATBOT
discuter_avec_chatbot(role="client")

💬 Chatbot Bloudan – mode client
Écris 'exit' pour quitter.

🤖 Bot (intent=salutation, lang=fr) : Bonjour 👋 Bienvenue chez Bloudan Restaurant. Comment je peux t’aider ?
🧠 Sentiment : NEUTRAL (score=0.6)
------------------------------------------------------------
🤖 Bot (intent=faire_commande, lang=de) : ✅ Natürlich. Sag mir das Gericht und die Menge.
🧠 Sentiment : NEUTRAL (score=0.6)
------------------------------------------------------------